version: "3.7"

services:
  php-apache:
    build:
      context: .
      dockerfile: ./apache/Dockerfile
    container_name: php-apache
    dns:
      - 8.8.8.8
      - 8.8.4.4
    env_file: .env
    volumes:
      - ${PROJECT_ROOT}/docroot/tripal4:/var/www/docroot
    ports:
      - "8080:80"
    depends_on:
      - postgres

  postgres:
    image: postgres:${POSTGRES_VERSION:-latest}
    container_name: postgres
    restart: always
    env_file: .env
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mapman:
    build: ./mapman
    container_name: mapman
    volumes:
      - ${PROJECT_ROOT}/mapman/usadellab.github.io/MapManJS:/usr/local/apache2/htdocs/
    ports:
      - "3000:80"

volumes:
  data: