version: "3.7"
services:
  php:
    build: 
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${PROJECT_ROOT}/docroot/tripal4:/var/www/bioinformatics/docroot/tripal4
    container_name: php

  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - postgres
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ${PROJECT_ROOT}/docroot/tripal4:/var/www/bioinformatics/docroot/tripal4
      - ${PROJECT_ROOT}/apache:/var/www/bioinformatics/apache
      - ./apache/local.apache.conf:/usr/local/apache2/conf/local.apache.conf
    container_name: apache

  postgres:
    image: postgres:${POSTGRES_VERSION:-latest}
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    container_name: postgres

  mapman:
    build: ./mapman
    container_name: mapman
    ports:
      - "3000:80"
    networks:
      - frontend
    volumes:
      - ${PROJECT_ROOT}/mapman/usadellab.github.io/MapManJS:/usr/local/apache2/htdocs/

networks:
  frontend:
    driver: bridge
    name: bioinformatics_frontend
  backend:
    driver: bridge
    name: bioinformatics_backend

volumes:
  data: